### ISSUE TITLE
Warning: Section lacks heading

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-ruchikatokish/960GridSystem#1]
Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

From line 199, column 2; to line 199, column 50

ection> ↩	<section class="grid_12" id="combined-section-1">↩	<sec

Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

From line 272, column 2; to line 272, column 40

tion-2">↩	<section class="grid_6 alpha" id="map">↩			<i

Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

From line 280, column 2; to line 280, column 10

section>↩	<section>↩		Nam

Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

From line 275, column 2; to line 275, column 48

ection>	↩	<section class="grid_6 omega" id="write-to-us">↩	<sec

Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

From line 271, column 2; to line 271, column 50

section>↩	<section class="grid_12" id="combined-section-2">↩	<sec

Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

From line 291, column 4; to line 291, column 50

r_12">↩			<section class="grid_12" id="footer-section-1">↩				<

Warning: Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections.

From line 308, column 4; to line 308, column 50

		<hr>↩			<section class="grid_12" id="footer-section-2">↩

**Comment by techsquad-ruchikatokish** [comment]
Checked in the new code after removing these warnings.
Fix : Replaced section tags with div tags.
