### ISSUE TITLE
unnecessary files and folders included

### ISSUE THREAD

**Issue by ms-tech-geek** [ibigrock-ruchikatokish/960GridSystem#4]
![image](https://user-images.githubusercontent.com/27997683/29056809-509ae33a-7c23-11e7-83d0-f9051f147992.png)

![image](https://user-images.githubusercontent.com/27997683/29056823-6cfb0604-7c23-11e7-8c73-d59ed6f2b7f3.png)

**Comment by techsquad-ruchikatokish** [comment]
Removed unused files and folders
